#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q commit luci

	uci -q set system.@imm_init[0].lang="1"
	uci -q commit system
fi

#if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
#	uci -q set fstab.@global[0].anon_mount="1"
#	uci -q commit fstab

#	uci -q set system.@imm_init[0].anon_mount="1"
#	uci -q commit system
#fi

ln -sf "/sbin/ip" "/usr/bin/ip"

[ ! -e "/bin/bash" ] || sed -i "s|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g" "/etc/passwd"
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='ImmortalWrt 21.02 Compile By Zy143L '" >> /etc/openwrt_release
sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

mv /sbin/tempinfo /sbin/tempinfo2

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
